version: '3.1'

services:
  db:
    image: mysql
#    volumes:
#      - dbbase:/var/lib/mysql
    ports:
      - "63972:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

#volumes:
#  ddbase: